# Generated by Django 2.2.7 on 2019-12-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodid', models.PositiveIntegerField()),
                ('sizeid', models.PositiveIntegerField()),
                ('colorid', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.UserInfo')),
            ],
            options={
                'unique_together': {('goodid', 'colorid', 'sizeid')},
            },
        ),
    ]
